name: train-hyperparameter-tune-deploy-with-tensorflow
dependencies:
- numpy
- tensorflow
- matplotlib
- pip:
  - azureml-sdk
  - azureml-widgets
  - pandas
  - keras
  - tensorflow-gpu
  - matplotlib
  - azureml-dataprep
  - fuse
